name: 4denoise-main
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.11.*
  - matplotlib=3.8.*
  - scikit-image=0.22.*
  - scikit-learn=1.4.*
  - h5py=3.10.*
  - tqdm=4.66.*
  - jupyterlab=4.2.*
  - ipykernel=6.29.*
  - notebook=7.3.2
  - jupyterlab=4.2.*
  - py-opencv=4.10.*      
  - pip
  - pip:
      - py4dstem==0.14.18
      - ncempy==1.11.1
      - emdfile==0.0.16
      - matplotlib-scalebar==0.9.0
